SELECT COUNT(*) AS Transactions, DATE(CRSTAMP) AS Date,CRSIGN AS User
FROM ACCEPT.PITCLGG	
WHERE DATE(CRSTAMP) >= '2020-09-15'	
AND CRSIGN = 'acaprims'
AND SEQNO = 1
GROUP BY DATE(CRSTAMP),CRSIGN
WITH UR;